!     -----------------------------------------------------------------
NAMELIST/NAERAD/&
&  LERAD1H, LERADHS, LEPO3RA, LRADLB , LONEWSW &
&, LCCNL  , LCCNO  , LECSRAD, LRAYL  , LRRTM  , LSRTM  &
&, LHVOLCA, LNEWAER, LDIFFC , LEMODAL, LNOTROAER &
&, LRADONDEM &
&, LPERPET &
&, NICEOPT, NLIQOPT, NMCICA , NRADIP , NRADLP &
&, NAER   , NMODE  , NOZOCL , NINHOM , NLAYINH &
&, NOVLP  , NLW    , NSW    , NRADFR , NLNGR1H &
&, NRADPFR, NRADPLA, NRINT  , NRPROMA, NCSRADF &
&, NRADINT, NRADRES, NGHGRAD, &
&  CRTABLEDIR, CRTABLEFIL &
&, RCCNSEA, RCCNLND, NPERTAER, NPERTOZ &
&, RPERTOZ, RLWINHF, RSWINHF, RRe2De , RMINICE &
&, RCCO2  , RCCH4  , RCN2O  , RCCFC11, RCCFC12 &
&, NHINCSOL,LECO2VAR,LHGHG  , NSCEN   &
&, LEDBUG , LESO4HIS &
&, LUVPROC, LUVTDEP, LUVDBG , NUV    , NUVTIM , NRADUV , RUVLAM, RMUZUV
!     -----------------------------------------------------------------



