IFS	=	source.a

include ../options.$(ARCH)

SOURCE	=\
aer_rad.F90 aer_rad.F90.orig cloudaer.F90 legtri.F90 legtriv.F90 \
main.F90.orig mcica_cld_generator.F90 mcica_cld_generator.F90.orig \
mcica_cld_gen.F90 parkind1.F90.orig qsat.F90 radaca.F90 radact.F90 \
radghg.F90 radina.F90 radlsw.F90 radlsw.F90.orig radlswm.F90 \
radlswr.F90 radlswr.F90.orig radozc.F90 rrtm_cmbgb10.F90 \
rrtm_cmbgb11.F90 rrtm_cmbgb12.F90 rrtm_cmbgb13.F90 rrtm_cmbgb14.F90 \
rrtm_cmbgb15.F90 rrtm_cmbgb16.F90 rrtm_cmbgb1.F90 rrtm_cmbgb2.F90 \
rrtm_cmbgb3.F90 rrtm_cmbgb4.F90 rrtm_cmbgb5.F90 rrtm_cmbgb6.F90 \
rrtm_cmbgb7.F90 rrtm_cmbgb8.F90 rrtm_cmbgb9.F90 rrtm_ecrt_140gp.F90 \
rrtm_ecrt_140gp_mcica.F90 rrtm_gasabs1a_140gp.F90 rrtm_init_140gp.F90 \
rrtm_kgb10.F90 rrtm_kgb11.F90 rrtm_kgb12.F90 rrtm_kgb13.F90 rrtm_kgb14.F90 \
rrtm_kgb15.F90 rrtm_kgb16.F90 rrtm_kgb1.F90 rrtm_kgb2.F90 rrtm_kgb3.F90 \
rrtm_kgb4.F90 rrtm_kgb5.F90 rrtm_kgb6.F90 rrtm_kgb7.F90 rrtm_kgb8.F90 \
rrtm_kgb9.F90 rrtm_rrtm_140gp.F90 rrtm_rrtm_140gp_mcica.F90 \
rrtm_rrtm_140gp_mcica.F90.orig rrtm_rtrn1a_140gp.F90 \
rrtm_rtrn1a_140gp.F90.orig rrtm_rtrn1a_140gp_mcica.F90 \
rrtm_setcoef_140gp.F90 rrtm_taumol10.F90 rrtm_taumol11.F90 \
rrtm_taumol12.F90 rrtm_taumol13.F90 rrtm_taumol14.F90 rrtm_taumol15.F90 \
rrtm_taumol16.F90 rrtm_taumol1.F90 rrtm_taumol2.F90 rrtm_taumol3.F90 \
rrtm_taumol4.F90 rrtm_taumol5.F90 rrtm_taumol6.F90 rrtm_taumol7.F90 \
rrtm_taumol8.F90 rrtm_taumol9.F90 satur.F90 setran.F90 source.a \
srtm_cldprop.F90 srtm_cmbgb16.F90 srtm_cmbgb17.F90 srtm_cmbgb18.F90 \
srtm_cmbgb19.F90 srtm_cmbgb20.F90 srtm_cmbgb21.F90 srtm_cmbgb22.F90 \
srtm_cmbgb23.F90 srtm_cmbgb24.F90 srtm_cmbgb25.F90 srtm_cmbgb26.F90 \
srtm_cmbgb27.F90 srtm_cmbgb28.F90 srtm_cmbgb29.F90 srtm_init.F90 \
srtm_kgb16.F90 srtm_kgb17.F90 srtm_kgb18.F90 srtm_kgb19.F90 \
srtm_kgb20.F90 srtm_kgb21.F90 srtm_kgb22.F90 srtm_kgb23.F90 srtm_kgb24.F90 \
srtm_kgb25.F90 srtm_kgb26.F90 srtm_kgb27.F90 srtm_kgb28.F90 srtm_kgb29.F90 \
srtm_reftra.F90 srtm_reftra.F90.orig srtm_setcoef.F90 srtm_spcvrt.F90 \
srtm_spcvrt.F90.orig srtm_spcvrt_mcica.F90 srtm_spcvrt_mcica.F90.orig \
srtm_srtm_224gp.F90 srtm_srtm_224gp.F90.orig srtm_srtm_224gp_mcica.F90 \
srtm_srtm_224gp_mcica.F90.orig srtm_taumol16.F90 srtm_taumol17.F90 \
srtm_taumol18.F90 srtm_taumol19.F90 srtm_taumol20.F90 srtm_taumol21.F90 \
srtm_taumol22.F90 srtm_taumol23.F90 srtm_taumol24.F90 srtm_taumol25.F90 \
srtm_taumol26.F90 srtm_taumol27.F90 srtm_taumol28.F90 srtm_taumol29.F90 \
srtm_vrtqdr.F90 srtm_vrtqdr.F90.orig suaerh.F90 suaerl.F90 su_aerop.F90 \
su_aerp.F90 suaersn.F90 suaersn.F90.orig suaerv.F90 su_aerw.F90 \
su_c11clim.F90 su_c12clim.F90 su_c22clim.F90 su_ccl4clim.F90 \
su_ch4clim.F90 sucld.F90 suclopn.F90 suclopn.F90.orig su_co2clim.F90 \
sucst.F90 sucst.F90.orig suecaebc.F90 suecaec.F90 suecaec.F90.Andrea \
suecaec.F90.orig suecaeor.F90 suecaesd.F90 suecaess.F90 suecaesu.F90 \
suecozc.F90 suecozo.F90 su_gch4clim.F90 su_gch4clim.F90.orig \
su_gco2clim.F90 su_gco2clim.F90.orig su_ghgclim.F90 su_gozoclim.F90 \
su_gozoclim.F90.orig sulwn.F90 su_mcica.F90 su_n2oclim.F90 su_no2clim.F90 \
su_ozoclim.F90 surdi.F90 surrtab.F90 surrtftr.F90 surrtpk.F90 \
surrtrf.F90 su_so4_A1B2000.F90 su_so4_A1B2010.F90 su_so4_A1B2020.F90 \
su_so4_A1B2030.F90 su_so4_A1B2040.F90 su_so4_A1B2050.F90 \
su_so4_A1B2060.F90 su_so4_A1B2070.F90 su_so4_A1B2080.F90 \
su_so4_A1B2090.F90 su_so4_A1B2100.F90 su_so4_obs1920.F90 \
su_so4_obs1930.F90 su_so4_obs1940.F90 su_so4_obs1950.F90 \
su_so4_obs1960.F90 su_so4_obs1970.F90 su_so4_obs1980.F90 \
su_so4_obs1990.F90 susrtaer.F90 susrtalb.F90 susrtcop.F90 susrtm.F90 \
susrtop.F90 suswn.F90 suswn.F90.orig su_uvradi.F90 updcal.F90

OBJECTS1	=	$(SOURCE:.f=.o)
OBJECTS2	=	$(SOURCE:.F90=.o)
OBJECTS = $(OBJECTS1) $(OBJECTS2)

.SUFFIXES:
.SUFFIXES:	.o .f .F90

.f.o :
	$(FC) -c $(FFLAGS) $(CP_OPT) $*.f
.F90.o :
	$(FC) -c $(FFLAGS) $(CP_OPT) $*.F90

all:	$(OBJECTS)
	touch source.a

clean:
	 rm -f $(OBJECTS)
